# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:    
    - task: SSH@0
      inputs:
        sshEndpoint: 'JobServerVM'
        runOptions: 'commands'
        commands: 'echo pong'
        readyTimeout: '20000'
      